#
# Copyright (c) 2021 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Dependencies for APP_EVENT_MANAGER and CAF
CONFIG_HEAP_MEM_POOL_SIZE=2048

# Enable logging
CONFIG_LOG=y
CONFIG_UART_CONSOLE=n
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y

# Enable CAF
CONFIG_CAF=y

# Dependencies for CAF_BUTTONS 
CONFIG_CAF_BUTTONS=y
CONFIG_CAF_BUTTONS_POLARITY_INVERSED=y

# Dependencies for CAF_LEDS
CONFIG_CAF_LEDS=y
CONFIG_LED=y
CONFIG_PWM=y

# Application specific options
CONFIG_CAF_LED_EVENTS=y
CONFIG_CAF_CUSTOM_LED_STATE=y
